# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main", "FSharp"]
  pull_request:
    branches: ["main", "FSharp"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Restore tools
        run: dotnet tool restore
        working-directory: ./CampaignManager.Frontend/src
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install Node dependencies
        run: npm install
      - name: Build Backend
        run: dotnet build --no-restore
      - name: Build Frontend
        run: npm run build
        working-directory: ./CampaignManager.Frontend/src
